effects:
  teleport:
    enabled: true
    default-cosmetic: teleport_mira
    visual:
      enabled: true
    audio:
      enabled: true
    ring-points: 36
    ring-radius: 1.0
    ring-spacing: 0.55
    base-y-offset: 0.15
  fly:
    enabled: true
    default-cosmetic: fly_white
    throttle-millis: 100
    count: 2
    y-offset: -0.15
    dust-size: 0.8
  trail:
    enabled: true
    throttle-millis: 250
  join:
    enabled: true
  kill:
    enabled: true

messages:
  prefix: '&5&lMira &8&l>> &r'
